nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs

packageExtensions:
  "@mui/core@*":
    dependencies:
      "@mui/system": "*"

    peerDependencies:
      "@emotion/styled": "*"
      "@emotion/react": "*"

  "@nestjs/graphql@*":
    peerDependencies:
      class-transformer: "*"
      class-validator: "*"

  "@nestjs/serve-static@*":
    peerDependencies:
      express: "*"

  "graphql.macro@*":
    peerDependencies:
      "@babel/core": "*"
      "@babel/runtime": "*"
      graphql: "*"
