name: "Publish"

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - uses: actions/cache@v2.1.5
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install

      - name: Build
        run: yarn workspaces foreach --no-private -ptv run build

      - name: Apply version update
        run: yarn version apply --all

      - name: Commit
        run: |
          git config --global user.name 'Boobrie'
          git config --global user.email 'boobrie@users.noreply.github.com'

          git commit -am "update(workspace): update version numbers"

      - name: Publish
        run: yarn workspaces foreach --no-private npm publish --access public --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push
        run: git push
