name: 'Publish'

on:
  push:
    branches: [ master ]

  milestone:
    types: [ closed ]

jobs:
  setup:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Publish only the latest commit
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: List workspaces to lint
        id: lint
        run: echo "::set-output name=matrix::$(yarn jill list --with-script lint --json)"

      - name: List workspaces to test
        id: test
        run: echo "::set-output name=matrix::$(yarn jill list --with-script test --json)"

    outputs:
      matrix-lint: ${{ steps.lint.outputs.matrix }}
      matrix-test: ${{ steps.test.outputs.matrix }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn jill each build

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: packages/*/dist/*

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{ fromJson(needs.setup.outputs.matrix-lint)[0] }}

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix-lint) }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn workspace ${{ matrix.name }} lint

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [setup] #[setup, tests, publish]
    if: ${{ fromJson(needs.setup.outputs.matrix-test)[0] }}

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix-test) }}

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: master
          fetch-depth: 0

#      - name: Download test coverage
#        uses: actions/download-artifact@v2
#        continue-on-error: true
#        with:
#          name: ${{ matrix.slug }}-coverage
#          path: ${{ matrix.root }}/coverage

      - name: Load package.json
        id: info
        run: echo ::set-output name=package::`cat ${{ matrix.root }}/package.json`

      - name: Sonarcloud
        uses: sonarsource/sonarcloud-github-action@v1.6
        with:
          projectBaseDir: ${{ matrix.root }}
          args: >
            -Dsonar.projectVersion=${{ fromJSON(steps.info.outputs.package).version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
