name: "Publish"

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install

      - name: Lint
        run: |
          yarn workspace @jujulego/janus lint
          yarn workspace @jujulego/janus-common lint
          yarn workspace @jujulego/janus-config lint
          yarn workspace @jujulego/janus-front lint
          yarn workspace @jujulego/janus-gate lint
          yarn workspace @jujulego/janus-proxy lint

  publish:
    runs-on: ubuntu-latest
    environment: npm
    needs: ['lint']

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Apply version update
        run: yarn version apply --all

      - name: Commit
        run: |
          git config --global user.name 'Boobrie'
          git config --global user.email 'boobrie@users.noreply.github.com'

          if `git diff --quiet --exit-code`
          then
            echo "::warning::Nothing changed !"
          else
            git commit -am "update(workspace): update version numbers"
          fi

      - name: Publish
        run: yarn workspaces foreach --no-private npm publish --access public --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push
        run: git push
