name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

jobs:
  version:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Version check
        run: yarn version check

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - "@jujulego/janus"
          - "@jujulego/janus-common"
          - "@jujulego/janus-config"
          - "@jujulego/janus-front"
          - "@jujulego/janus-gate"
          - "@jujulego/janus-proxy"

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: neoxia/is-workspace-affected@v1.0
        id: affected
        with:
          workspace: ${{ matrix.package }}
          base: master

      - name: Use Node.js 14.x
        if: steps.affected.outputs.affected
        uses: actions/setup-node@v2.3.1
        with:
          node-version: 14.x
          cache: yarn

      - name: Install
        if: steps.affected.outputs.affected
        run: yarn install

      - name: Lint
        if: steps.affected.outputs.affected
        run: yarn workspace ${{ matrix.package }} lint

  build:
    runs-on: ubuntu-latest
    needs: ['lint']

    strategy:
      matrix:
        node: [12, 14]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node }}.x
        uses: actions/setup-node@v2.3.1
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
