name: 'Pull Request'

on:
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - run: git fetch origin ${{ github.base_ref }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: List workspaces to lint
        id: lint
        run: echo "::set-output name=matrix::$(yarn jill list --with-script lint --affected origin/${{ github.base_ref }} --json)"

      - name: List workspaces to test
        id: test
        run: echo "::set-output name=matrix::$(yarn jill list --with-script test --affected origin/${{ github.base_ref }} --json)"

    outputs:
      matrix-lint: ${{ steps.lint.outputs.matrix }}
      matrix-test: ${{ steps.test.outputs.matrix }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn jill each build --affected origin/${{ github.base_ref }}

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: packages/*/dist/*

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{ fromJson(needs.setup.outputs.matrix-lint)[0] }}

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix-lint) }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn workspace ${{ matrix.name }} lint

  tests:
    runs-on: ubuntu-latest
    needs: [setup, build]
    if: ${{ fromJson(needs.setup.outputs.matrix-test)[0] }}

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix-test) }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: packages

      - name: Test
        run: yarn workspace ${{ matrix.name }} test

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.slug }}-coverage
          path: ${{ matrix.root }}/coverage

  version:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    needs: [ lint, tests ]

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Version check
        run: yarn version check

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [setup, tests]
    if: ${{ fromJson(needs.setup.outputs.matrix-test)[0] && !startsWith(github.head_ref, 'renovate/') }}

    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix-test) }}

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Download test coverage
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: ${{ matrix.slug }}-coverage
          path: ${{ matrix.root }}/coverage

      - name: Load package.json
        id: info
        run: echo ::set-output name=package::`cat ${{ matrix.root }}/package.json`

      - name: Sonarcloud
        uses: sonarsource/sonarcloud-github-action@v1.6
        with:
          projectBaseDir: ${{ matrix.root }}
          args: >
            -Dsonar.projectVersion=${{ fromJSON(steps.info.outputs.package).version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
