name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version check
        run: yarn version check

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - "@jujulego/janus-gate"
          - "@jujulego/janus-proxy"

    steps:
      - uses: actions/checkout@v2

      - uses: julien-capellari/is-workspace-affected@v1.0
        id: affected
        with:
          workspace: ${{ matrix.package }}
          base: master

      - name: Install
        run: yarn install

      - name: Build
        if: steps.affected.outputs.affected
        run: yarn workspace ${{ matrix.package }} build
