name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Version check
        run: yarn version check

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - "@jujulego/janus"
          - "@jujulego/janus-config"
          - "@jujulego/janus-front"
          - "@jujulego/janus-gate"
          - "@jujulego/janus-proxy"
          - "@jujulego/janus-types"

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: julien-capellari/is-workspace-affected@v1.0
        id: affected
        with:
          workspace: ${{ matrix.package }}
          base: master

      - name: Use Node.js 14.x
        if: steps.affected.outputs.affected
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - uses: actions/cache@v2.1.5
        if: steps.affected.outputs.affected
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        if: steps.affected.outputs.affected
        run: yarn install

      - name: Build
        if: steps.affected.outputs.affected
        run: yarn workspace ${{ matrix.package }} workspaces foreach -pvR --topological-dev run build
