name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Version check
        run: yarn version check
